# Generated by Django 5.2 on 2026-01-03 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Gatunek zwierzęcia',
                'verbose_name_plural': 'Gatunki zwierząt',
                'indexes': [models.Index(fields=['name'], name='barfik_syst_name_7abe62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='barfik_system.animaltype')),
            ],
            options={
                'verbose_name': 'Zwierzę',
                'verbose_name_plural': 'Zwierzęta',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('permission', models.CharField(choices=[('READ_ONLY', 'Tylko odczyt'), ('EDIT', 'Edycja')], default='READ_ONLY', max_length=16)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='barfik_system.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Współpraca',
                'verbose_name_plural': 'Współprace',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_daily_mass', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='barfik_system.animal')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Diety',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria składnika',
                'verbose_name_plural': 'Kategorie składników',
                'indexes': [models.Index(fields=['code'], name='barfik_syst_code_db2678_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
                ('diets', models.ManyToManyField(related_name='shopping_lists', to='barfik_system.diet')),
            ],
            options={
                'verbose_name': 'Lista zakupów',
                'verbose_name_plural': 'Listy zakupów',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(1e-06)])),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
                'indexes': [models.Index(fields=['name'], name='barfik_syst_name_ae2df8_idx'), models.Index(fields=['symbol'], name='barfik_syst_symbol_1ec792_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ingredient_name', models.CharField(max_length=128)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('is_checked', models.BooleanField(db_index=True, default=False)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barfik_system.shoppinglist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list_items', to='barfik_system.unit')),
            ],
            options={
                'verbose_name': 'Pozycja listy zakupów',
                'verbose_name_plural': 'Pozycje list zakupów',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=128)),
                ('cooking_method', models.CharField(choices=[('raw', 'Surowe'), ('cooked', 'Gotowane')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('amount_in_base_unit', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='barfik_system.diet')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='barfik_system.ingredientcategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='barfik_system.unit')),
            ],
            options={
                'verbose_name': 'Składnik',
                'verbose_name_plural': 'Składniki',
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner', 'is_active'], name='barfik_syst_owner_i_4d3701_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'is_active'], name='barfik_syst_species_ffa401_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['animal', 'user', 'is_active'], name='barfik_syst_animal__adafa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('animal', 'user'), name='uix_collab_active_pair'),
        ),
        migrations.AddIndex(
            model_name='diet',
            index=models.Index(fields=['animal', 'is_active'], name='barfik_syst_animal__6b3375_idx'),
        ),
        migrations.AddIndex(
            model_name='diet',
            index=models.Index(fields=['animal', 'start_date', 'end_date'], name='barfik_syst_animal__80430b_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['created_by', 'is_active'], name='barfik_syst_created_13b6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['is_completed', 'is_active'], name='barfik_syst_is_comp_52a325_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'is_active'], name='barfik_syst_shoppin_5e8c31_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'is_checked'], name='barfik_syst_shoppin_5ee932_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['diet', 'is_active'], name='barfik_syst_diet_id_6897fa_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category', 'is_active'], name='barfik_syst_categor_a172d2_idx'),
        ),
    ]
