# Generated by Django 5.2 on 2026-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barfik_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
