# Generated by Django 5.2 on 2026-01-03 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barfik_system', '0002_diet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='days_count',
            field=models.IntegerField(default=1, help_text='Liczba dni dla której generowana jest lista zakupów', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
