# Generated by Django 5.2 on 2026-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barfik_system', '0003_shoppinglist_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
