# Generated by Django 5.2 on 2026-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barfik_system', '0004_shoppinglistitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='permission',
            field=models.CharField(choices=[('READ_ONLY', 'Tylko odczyt'), ('EDIT', 'Edycja')], default='EDIT', max_length=16),
        ),
    ]
