/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/animal-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista gatunków zwierząt */
        get: operations["animal_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animal-types/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły gatunku */
        get: operations["animal_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista zwierząt dostępnych dla użytkownika */
        get: operations["animals_list"];
        put?: never;
        /** @description Dodaj nowe zwierzę */
        post: operations["animals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animals/{animal_id}/collaborations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista współpracowników dla zwierzęcia */
        get: operations["animals_collaborations_list"];
        put?: never;
        /** @description Dodaj współpracownika */
        post: operations["animals_collaborations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animals/{animal_id}/collaborations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Zarządzanie współpracownikami zwierzęcia. */
        get: operations["animals_collaborations_retrieve"];
        put?: never;
        post?: never;
        /** @description Usuń współpracę */
        delete: operations["animals_collaborations_destroy"];
        options?: never;
        head?: never;
        /** @description Zaktualizuj uprawnienia (częściowo) */
        patch: operations["animals_collaborations_partial_update"];
        trace?: never;
    };
    "/api/animals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły zwierzęcia */
        get: operations["animals_retrieve"];
        /** @description Zaktualizuj zwierzę */
        put: operations["animals_update"];
        post?: never;
        /** @description Usuń zwierzę (soft delete) */
        delete: operations["animals_destroy"];
        options?: never;
        head?: never;
        /** @description Zaktualizuj zwierzę (częściowo) */
        patch: operations["animals_partial_update"];
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Zarejestruj nowego użytkownika */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pobierz statystyki i alerty dla dashboardu użytkownika */
        get: operations["dashboard_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista diet dostępnych dla użytkownika */
        get: operations["diets_list"];
        put?: never;
        /** @description Dodaj nową dietę */
        post: operations["diets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diets/{diet_id}/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista składników dla diety */
        get: operations["diets_ingredients_list"];
        put?: never;
        /** @description Dodaj składnik do diety */
        post: operations["diets_ingredients_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diets/{diet_id}/ingredients/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły składnika */
        get: operations["diets_ingredients_retrieve"];
        /** @description Zaktualizuj składnik */
        put: operations["diets_ingredients_update"];
        post?: never;
        /** @description Usuń składnik (soft delete) */
        delete: operations["diets_ingredients_destroy"];
        options?: never;
        head?: never;
        /** @description Zaktualizuj składnik (częściowo) */
        patch: operations["diets_ingredients_partial_update"];
        trace?: never;
    };
    "/api/diets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły diety ze składnikami */
        get: operations["diets_retrieve"];
        /** @description Zaktualizuj dietę */
        put: operations["diets_update"];
        post?: never;
        /** @description Usuń dietę (soft delete) */
        delete: operations["diets_destroy"];
        options?: never;
        head?: never;
        /** @description Zaktualizuj dietę (częściowo) */
        patch: operations["diets_partial_update"];
        trace?: never;
    };
    "/api/ingredient-categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista kategorii składników */
        get: operations["ingredient_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredient-categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły kategorii */
        get: operations["ingredient_categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-lists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista zakupów użytkownika */
        get: operations["shopping_lists_list"];
        put?: never;
        /** @description Wygeneruj nową listę zakupów */
        post: operations["shopping_lists_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-lists/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły listy zakupów */
        get: operations["shopping_lists_retrieve"];
        /** @description Zaktualizuj listę zakupów */
        put: operations["shopping_lists_update"];
        post?: never;
        /** @description Usuń listę zakupów */
        delete: operations["shopping_lists_destroy"];
        options?: never;
        head?: never;
        /** @description Zaktualizuj listę zakupów (częściowo) */
        patch: operations["shopping_lists_partial_update"];
        trace?: never;
    };
    "/api/shopping-lists/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Oznacz listę jako ukończoną */
        post: operations["shopping_lists_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-lists/{id}/uncomplete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Oznacz listę jako nieukończoną */
        post: operations["shopping_lists_uncomplete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-lists/{shopping_list_id}/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista pozycji zakupów */
        get: operations["shopping_lists_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-lists/{shopping_list_id}/items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły pozycji */
        get: operations["shopping_lists_items_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Zaktualizuj pozycję (częściowo) */
        patch: operations["shopping_lists_items_partial_update"];
        trace?: never;
    };
    "/api/shopping-lists/{shopping_list_id}/items/{id}/check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Zaznacz/odznacz pozycję jako kupioną */
        post: operations["shopping_lists_items_check_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista jednostek miar */
        get: operations["units_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Szczegóły jednostki */
        get: operations["units_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pobierz profil zalogowanego użytkownika */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Zaktualizuj profil zalogowanego użytkownika */
        patch: operations["users_me_partial_update"];
        trace?: never;
    };
    "/api/users/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search for user by email address */
        get: operations["users_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer dla tworzenia zwierzęcia. */
        AnimalCreate: {
            species_id: number;
            name: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            note?: string;
        };
        /** @description Serializer dla tworzenia zwierzęcia. */
        AnimalCreateRequest: {
            species_id: number;
            name: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            note?: string;
        };
        /** @description Serializer dla szczegółów zwierzęcia. */
        AnimalDetail: {
            readonly id: number;
            readonly owner: number;
            /** Format: email */
            readonly owner_email: string;
            readonly species: components["schemas"]["AnimalType"];
            name: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            note?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla szczegółów zwierzęcia. */
        AnimalDetailRequest: {
            species_id: number;
            name: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            note?: string;
            is_active?: boolean;
        };
        /** @description Serializer dla listy zwierząt (uproszczony). */
        AnimalList: {
            readonly id: number;
            readonly owner: number;
            /** Format: email */
            readonly owner_email: string;
            readonly species: components["schemas"]["AnimalType"];
            name: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla gatunków zwierząt. */
        AnimalType: {
            readonly id: number;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla gatunków zwierząt. */
        AnimalTypeRequest: {
            name: string;
        };
        /** @description Serializer dla alertu o zwierzęciu bez diety. */
        AnimalWithoutDietAlert: {
            id: number;
            name: string;
            species: string;
        };
        /** @description Serializer dla współpracy. */
        Collaboration: {
            readonly id: number;
            readonly animal: number;
            readonly animal_name: string;
            user: number;
            /** Format: email */
            readonly user_email: string;
            permission?: components["schemas"]["PermissionEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla współpracy. */
        CollaborationRequest: {
            user: number;
            permission?: components["schemas"]["PermissionEnum"];
            is_active?: boolean;
        };
        /**
         * @description * `raw` - Surowe
         *     * `cooked` - Gotowane
         * @enum {string}
         */
        CookingMethodEnum: "raw" | "cooked";
        /** @description Główny serializer dla dashboardu. */
        Dashboard: {
            stats: components["schemas"]["DashboardStats"];
            alerts: components["schemas"]["DashboardAlerts"];
        };
        /** @description Serializer dla alertów dashboardu. */
        DashboardAlerts: {
            animals_without_diet: components["schemas"]["AnimalWithoutDietAlert"][];
            expiring_diets: components["schemas"]["ExpiringDietAlert"][];
            old_shopping_lists: components["schemas"]["OldShoppingListAlert"][];
        };
        /** @description Serializer dla statystyk dashboardu. */
        DashboardStats: {
            /** @description Liczba aktywnych zwierząt */
            animals_count: number;
            /** @description Liczba aktywnych diet */
            active_diets_count: number;
            /** @description Liczba diet wygasających w ciągu 7 dni */
            expiring_diets_count: number;
            /** @description Liczba aktywnych list zakupów */
            active_shopping_lists_count: number;
            /** @description Liczba ukończonych list w bieżącym miesiącu */
            completed_shopping_lists_count: number;
        };
        /** @description Serializer dla tworzenia diety. */
        DietCreate: {
            readonly id: number;
            animal_id: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
        };
        /** @description Serializer dla tworzenia diety. */
        DietCreateRequest: {
            animal_id: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
        };
        /** @description Serializer dla szczegółów diety z listą składników. */
        DietDetail: {
            readonly id: number;
            animal: number;
            readonly animal_name: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            /** Format: decimal */
            readonly total_daily_mass: string;
            description?: string;
            readonly ingredients: components["schemas"]["Ingredient"][];
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla szczegółów diety z listą składników. */
        DietDetailRequest: {
            animal: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            is_active?: boolean;
        };
        /** @description Serializer dla listy diet (uproszczony). */
        DietList: {
            readonly id: number;
            animal: number;
            readonly animal_name: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            /** Format: decimal */
            readonly total_daily_mass: string;
            description?: string;
            readonly ingredients_count: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla alertu o wygasającej diecie. */
        ExpiringDietAlert: {
            id: number;
            animal_id: number;
            animal_name: string;
            /** Format: date */
            end_date: string;
            days_left: number;
        };
        /** @description Serializer dla składników. */
        Ingredient: {
            readonly id: number;
            readonly diet: number;
            name: string;
            readonly category: components["schemas"]["IngredientCategory"];
            category_id?: number | null;
            cooking_method: components["schemas"]["CookingMethodEnum"];
            readonly unit: components["schemas"]["Unit"];
            /** Format: decimal */
            amount: string;
            /** Format: decimal */
            readonly amount_in_base_unit: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla kategorii składników. */
        IngredientCategory: {
            readonly id: number;
            code: string;
            name: string;
            description?: string;
        };
        /** @description Serializer dla kategorii składników. */
        IngredientCategoryRequest: {
            code: string;
            name: string;
            description?: string;
        };
        /** @description Serializer dla składników. */
        IngredientRequest: {
            name: string;
            category_id?: number | null;
            cooking_method: components["schemas"]["CookingMethodEnum"];
            unit_id: number;
            /** Format: decimal */
            amount: string;
            is_active?: boolean;
        };
        /** @description Serializer dla alertu o starej liście zakupów. */
        OldShoppingListAlert: {
            id: number;
            title: string;
            /** Format: date-time */
            created_at: string;
            days_old: number;
        };
        PaginatedAnimalListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AnimalList"][];
        };
        PaginatedAnimalTypeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AnimalType"][];
        };
        PaginatedCollaborationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Collaboration"][];
        };
        PaginatedDietListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DietList"][];
        };
        PaginatedIngredientCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IngredientCategory"][];
        };
        PaginatedIngredientList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Ingredient"][];
        };
        PaginatedShoppingListItemList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ShoppingListItem"][];
        };
        PaginatedShoppingListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ShoppingList"][];
        };
        PaginatedUnitList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Unit"][];
        };
        /** @description Serializer dla szczegółów zwierzęcia. */
        PatchedAnimalDetailRequest: {
            species_id?: number;
            name?: string;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: decimal */
            weight_kg?: string | null;
            note?: string;
            is_active?: boolean;
        };
        /** @description Serializer dla współpracy. */
        PatchedCollaborationRequest: {
            user?: number;
            permission?: components["schemas"]["PermissionEnum"];
            is_active?: boolean;
        };
        /** @description Serializer dla szczegółów diety z listą składników. */
        PatchedDietDetailRequest: {
            animal?: number;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            is_active?: boolean;
        };
        /** @description Serializer dla składników. */
        PatchedIngredientRequest: {
            name?: string;
            category_id?: number | null;
            cooking_method?: components["schemas"]["CookingMethodEnum"];
            unit_id?: number;
            /** Format: decimal */
            amount?: string;
            is_active?: boolean;
        };
        /** @description Serializer dla pozycji listy zakupów. */
        PatchedShoppingListItemRequest: {
            ingredient_name?: string;
            category?: string;
            /** Format: decimal */
            total_amount?: string;
            is_checked?: boolean;
            is_active?: boolean;
        };
        /** @description Serializer dla listy zakupów. */
        PatchedShoppingListRequest: {
            title?: string;
            /**
             * Format: int64
             * @description Liczba dni dla której generowana jest lista zakupów
             */
            days_count?: number;
            is_completed?: boolean;
            diets?: number[];
            is_active?: boolean;
        };
        /** @description Serializer dla profilu użytkownika. */
        PatchedUserRequest: {
            /**
             * Adres e-mail
             * Format: email
             */
            email?: string;
            /** Imię */
            first_name?: string;
            /** Nazwisko */
            last_name?: string;
            /**
             * Nazwa użytkownika
             * @description Wymagana. 150 lub mniej znaków. Jedynie litery, cyfry i @/./+/-/_.
             */
            username?: string;
        };
        /**
         * @description * `READ_ONLY` - Tylko odczyt
         *     * `EDIT` - Edycja
         * @enum {string}
         */
        PermissionEnum: "READ_ONLY" | "EDIT";
        /** @description Serializer dla listy zakupów. */
        ShoppingList: {
            readonly id: number;
            readonly created_by: number;
            title?: string;
            /**
             * Format: int64
             * @description Liczba dni dla której generowana jest lista zakupów
             */
            days_count: number;
            is_completed?: boolean;
            diets: number[];
            readonly diets_info: {
                id?: number;
                animal_name?: string;
                /** Format: date */
                start_date?: string;
                /** Format: date */
                end_date?: string | null;
            }[];
            readonly items: components["schemas"]["ShoppingListItem"][];
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla tworzenia listy zakupów. */
        ShoppingListCreate: {
            title?: string;
            diets: number[];
            /**
             * Format: int64
             * @description Liczba dni dla której generowana jest lista zakupów
             */
            days_count: number;
        };
        /** @description Serializer dla tworzenia listy zakupów. */
        ShoppingListCreateRequest: {
            title?: string;
            diets: number[];
            /**
             * Format: int64
             * @description Liczba dni dla której generowana jest lista zakupów
             */
            days_count: number;
        };
        /** @description Serializer dla pozycji listy zakupów. */
        ShoppingListItem: {
            readonly id: number;
            ingredient_name: string;
            category?: string;
            readonly unit: components["schemas"]["Unit"];
            /** Format: decimal */
            total_amount: string;
            is_checked?: boolean;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer dla pozycji listy zakupów. */
        ShoppingListItemRequest: {
            ingredient_name: string;
            category?: string;
            /** Format: decimal */
            total_amount: string;
            is_checked?: boolean;
            is_active?: boolean;
        };
        /** @description Serializer dla listy zakupów. */
        ShoppingListRequest: {
            title?: string;
            /**
             * Format: int64
             * @description Liczba dni dla której generowana jest lista zakupów
             */
            days_count: number;
            is_completed?: boolean;
            diets: number[];
            is_active?: boolean;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        /** @description Serializer dla jednostek miar. */
        Unit: {
            readonly id: number;
            name: string;
            symbol: string;
            /** Format: decimal */
            conversion_factor: string;
        };
        /** @description Serializer dla jednostek miar. */
        UnitRequest: {
            name: string;
            symbol: string;
            /** Format: decimal */
            conversion_factor: string;
        };
        /** @description Serializer dla profilu użytkownika. */
        User: {
            readonly id: number;
            /**
             * Adres e-mail
             * Format: email
             */
            email?: string;
            /** Imię */
            first_name?: string;
            /** Nazwisko */
            last_name?: string;
            /**
             * Nazwa użytkownika
             * @description Wymagana. 150 lub mniej znaków. Jedynie litery, cyfry i @/./+/-/_.
             */
            username: string;
        };
        /** @description Serializer dla rejestracji nowego użytkownika. */
        UserRegistrationRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** Imię */
            first_name?: string;
            /** Nazwisko */
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    animal_types_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnimalTypeList"];
                };
            };
        };
    };
    animal_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Gatunek zwierzęcia. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalType"];
                };
            };
        };
    };
    animals_list: {
        parameters: {
            query?: {
                /** @description Filtruj po statusie (true=aktywne, false=usunięte, brak=wszystkie) */
                active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Szukaj po nazwie */
                search?: string;
                /** @description Filtruj po gatunku */
                species_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnimalListList"];
                };
            };
        };
    };
    animals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnimalCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalCreate"];
                };
            };
        };
    };
    animals_collaborations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                animal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCollaborationList"];
                };
            };
        };
    };
    animals_collaborations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollaborationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collaboration"];
                };
            };
        };
    };
    animals_collaborations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collaboration"];
                };
            };
        };
    };
    animals_collaborations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    animals_collaborations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animal_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCollaborationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collaboration"];
                };
            };
        };
    };
    animals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Zwierzę. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDetail"];
                };
            };
        };
    };
    animals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Zwierzę. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnimalDetailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDetail"];
                };
            };
        };
    };
    animals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Zwierzę. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    animals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Zwierzę. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAnimalDetailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDetail"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistrationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    dashboard_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    diets_list: {
        parameters: {
            query?: {
                /** @description Filtruj po statusie aktywności */
                active?: boolean;
                /** @description Filtruj po zwierzęciu */
                animal_id?: number;
                /** @description Data zakończenia do */
                end_date__lte?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Data rozpoczęcia od */
                start_date__gte?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDietListList"];
                };
            };
        };
    };
    diets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DietCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietCreate"];
                };
            };
        };
    };
    diets_ingredients_list: {
        parameters: {
            query?: {
                /** @description Filtruj po kategorii */
                category_id?: number;
                /** @description Filtruj po metodzie (raw/cooked) */
                cooking_method?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Szukaj po nazwie */
                search?: string;
            };
            header?: never;
            path: {
                diet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngredientList"];
                };
            };
        };
    };
    diets_ingredients_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    diets_ingredients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diet_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    diets_ingredients_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diet_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    diets_ingredients_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diet_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diets_ingredients_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diet_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIngredientRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    diets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Dieta. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDetail"];
                };
            };
        };
    };
    diets_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Dieta. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DietDetailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDetail"];
                };
            };
        };
    };
    diets_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Dieta. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Dieta. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDietDetailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietDetail"];
                };
            };
        };
    };
    ingredient_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngredientCategoryList"];
                };
            };
        };
    };
    ingredient_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Kategoria składnika. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientCategory"];
                };
            };
        };
    };
    shopping_lists_list: {
        parameters: {
            query?: {
                /** @description Filtruj po statusie */
                is_completed?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShoppingListList"];
                };
            };
        };
    };
    shopping_lists_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingListCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListCreate"];
                };
            };
        };
    };
    shopping_lists_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
        };
    };
    shopping_lists_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingListRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
        };
    };
    shopping_lists_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shopping_lists_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShoppingListRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
        };
    };
    shopping_lists_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
        };
    };
    shopping_lists_uncomplete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Lista zakupów. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
        };
    };
    shopping_lists_items_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                shopping_list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShoppingListItemList"];
                };
            };
        };
    };
    shopping_lists_items_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                shopping_list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItem"];
                };
            };
        };
    };
    shopping_lists_items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                shopping_list_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShoppingListItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItem"];
                };
            };
        };
    };
    shopping_lists_items_check_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                shopping_list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItem"];
                };
            };
        };
    };
    units_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUnitList"];
                };
            };
        };
    };
    units_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Jednostka. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_search_retrieve: {
        parameters: {
            query: {
                /** @description Email address to search for */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
